### ISSUE TITLE
Relay Integration

### ISSUE THREAD

**Issue by cliedeman** [ovrsea/graphql-detect-unused-operations#19]
Has anyone tried using this with relay projects?

**Comment by eltonio450** [comment]
Hi Clie,

We use Apollo @ OVRSEA, but since we wrote this plugin, I think https://the-guild.dev/graphql/eslint/rules/no-unused-fields can be a good option aswell :)

**Comment by cliedeman** [comment]
Thanks ill give that a shot. I tried this plugin and it correctly plucked out all the fragments and queries but still got some false positives. Will dig deeper if I dont have luck with the unsed fields plugin
